### ISSUE TITLE
opsman login

### ISSUE THREAD

**Issue by agregory999** [patrickcrocker/pcf-stuff#17]
Can you document the login process? Seems we get something like this, even after logging in:
user@opsman:~/pcf-stuff$ ./opsman upload p-mysql-1.10.13.pivotal
./opsman: line 43: 1: UAA_ACCESS_TOKEN null or not set
Uploading tile: p-mysql-1.10.13.pivotal
######################################################################## 100.0%
user@opsman:~/pcf-stuff$

It finishes but the tile isn't showing in opsman UI.  I looked at the script for usage:
Usage: opsman <command> [options]
Examples:
  opsman login
  opsman upload cf-1.8.5-build.4.pivotal
  opsman upload bosh-stemcell-3363.24-vsphere-esxi-ubuntu-trusty-go_agent.tgz

Yet the login command (figured that may help) doesn't allow no arguments:

user@opsman:~/pcf-stuff$ ./opsman login
./opsman: line 106: $2: unbound variable

I got around it by adding garbage args and forcing the login:

user@opsman:~/pcf-stuff$ ./opsman login a a
Ops Manager User: admin
Ops Manager Pass:

Target: https://localhost/uaa

Successfully fetched token via owner password grant.
Target: https://localhost/uaa
Context: admin, from client opsman

User admin logged in successfully.
user@opsman:~/pcf-stuff$ ./opsman upload p-mysql-1.10.13.pivotal
Uploading tile: p-mysql-1.10.13.pivotal
######################################################################## 100.0%
user@opsman:~/pcf-stuff$

**Comment by patrickcrocker** [comment]
Fixed!  I had recently introduced strict bash mode for unassigned vars and didn't check the `login` command, sorry!

The `login` doesn't take any args and will prompt you for your Ops Manager creds.
